apiVersion: v1
kind: Service
metadata:
  name: python-calculator
  namespace: python-calculator

spec:
  type: ClusterIP

  selector:
    app: python-calculator

  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
